---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Load Scenario Variables
      ansible.builtin.include_vars: vars/main.yml
    - name: Check Downloaded Content
      ansible.builtin.stat:
        path: "{{ item.link }}"
      register: check_content
      loop: "{{ symlinks }}"
    - name: Assert Files Exist
      ansible.builtin.assert:
        that:
          - item.stat.exists
        msg: "{{ item.item.link }} does not exist."
      loop: "{{ check_content.results }}"
      when: item.item.target != symlinks[0].target
    - name: Assert Files Have Correct Attributes
      ansible.builtin.assert:
        that:
          - item.stat.pw_name == symlinks_user
          - item.stat.lnk_target == item.item.target
          - item.stat.path == item.item.link
        msg: "{{ item.item.link }} has wrong attributes."
      loop: "{{ check_content.results }}"
      when: item.item.target != symlinks[0].target
