---
# tasks file for role-symlinks

- name: Create Symlinks
  become: True
  become_user: "{{ symlinks_user }}"
  ansible.builtin.file:
    src: '{{ _role_symlinks_item.target }}'
    dest: '{{ _role_symlinks_item.link }}'
    force: '{{ false if "force" not in _role_symlinks_item else _role_symlinks_item.force }}'
    follow: '{{ true if "force" not in _role_symlinks_item else not _role_symlinks_item.force }}'
    state: link
  loop:
    "{{ symlinks }}"
  loop_control:
    loop_var: _role_symlinks_item
  tags:
    - symlinks
